import type { Metadata } from "next";
import {  Montserrat } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const montserrat = Montserrat({subsets: ['latin'], weight: "500"})

export const metadata: Metadata = {
  title: "Find Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
